### ISSUE TITLE
Cannot read property 'prepareInfo' of undefined

### ISSUE THREAD

**Issue by sudhanshu-15** [markosko/nativescript-hook-debug-production#1]
I did try using the plugin but it is throwing an error at me. This is what I am getting right now: Executing after-prepare hook from /Downloads/test/testdrawer/testbuildapp/hooks/after-prepare/‌​nativescript-hook-de‌​bug-production.js Cannot read property 'prepareInfo' of undefined

**Comment by markosko** [comment]
What `tns` command did you use when you get error and can add nativescript cli version too ?

**Comment by sudhanshu-15** [comment]
I used `tns run android` and also tried `tns debug android`. Using NativeScript CLI 2.3.0

**Comment by markosko** [comment]
I am updating hook for 2.3.0 version should be done in some minutes

**Comment by sudhanshu-15** [comment]
Thanks a lot 👍

**Comment by markosko** [comment]
Hello, you can try @1.0.2 version, it should be updated at npm right now.
