### ISSUE TITLE
Upgrade plugin for 2.5.0

### ISSUE THREAD

**Issue by sudhanshu-15** [markosko/nativescript-hook-debug-production#2]
The plugin is not working for NativeScript 2.5.0. I was wondering if it would be possible to get an update. 

- Also the tns uninstall for this plugin leaves the js file in hooks/after-prepare, which needs to be manually removed later.

- Code doesn't work as expected when you want to export a module like a constants module ( created for storing values). Code is unable to identify filename.debug.ts in this case.

Thanks a lot for this plugin, I just thought I would give some feedback to make it better.

**Comment by markosko** [comment]
Hello,
I got code for hooks/after-prepare deleting and for 2.5 version.
Your constants module is saved where ? Inside app folder ? And is it transpiled to filename.debug.js too ?
Or how you require that file ? `require("filename")` or something else ??

**Comment by sudhanshu-15** [comment]
Yes, the constants module is inside the app folder in a subfolder commons

![image](https://cloud.githubusercontent.com/assets/883233/22602917/3a40d1f0-ea13-11e6-8560-9e1170283de7.png)

This is how I am importing:
`import {BASE_PATH, POST_PATH, LOGIN_PATH} from "../../common/constants";`

Thanks a lot for looking into this.

**Comment by markosko** [comment]
and do u have `constats.debug.ts` too ?

**Comment by sudhanshu-15** [comment]
I had but it was not able to resolve it so had to remove it.

**Comment by markosko** [comment]
Probably as you want use `constats` even in debug release  as `constats.debug.js` will be `constats.js` while debug and not release mode

**Comment by sudhanshu-15** [comment]
Can you elaborate a little, I am sorry.

**Comment by markosko** [comment]
Simply always call for constats.js even if you want pick from debug file, after hook it will be only filename.extension 
![image](https://cloud.githubusercontent.com/assets/7886449/22604795/76359256-ea4d-11e6-9914-1837fcdd58f1.png)

**Comment by sudhanshu-15** [comment]
That is what I was doing, but it was not able resolve. My values were incorrect, that is why pointed it out. I will try replicating the issue again, and keep you posted.

**Comment by markosko** [comment]
And wrong while you was on NS 2.5 or before that ?

**Comment by sudhanshu-15** [comment]
I was using NS 2.3

**Comment by sudhanshu-15** [comment]
@markosko I was not able to replicate the issue, I would say the issue is resolved. Thank you so much for looking into this and thank you for the plugin. I am closing this issue.
