### ISSUE TITLE
BUG Not detecting release flags

### ISSUE THREAD

**Issue by danielgek** [markosko/nativescript-hook-debug-production#5]
Hi @markosko 
i was trying to use your plugin but it never recognized the `--release` flag

this  [if condition](https://github.com/markosko/nativescript-hook-debug-production/blob/master/after-prepare-hook.js#L16) is setting `release` to `false`

will summit pr with fix

**Comment by maxfriedmann** [comment]
any updates on this? the PR could get merged and make us all happy...

**Comment by sammoore** [comment]
Merged in #6, this ticket could probably be closed.
